#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# lint js and vue files
npx --no-install lint-staged

# lint only staged ruby files that still exist (not deleted)
STAGED_RB_FILES=$(git diff --name-only --cached --diff-filter=d | grep '\.rb$')
if [ -n "$STAGED_RB_FILES" ]; then
  echo "$STAGED_RB_FILES" | xargs bundle exec rubocop --force-exclusion -a || true
fi

# stage rubocop changes to files
git diff --name-only --cached | xargs -I {} sh -c 'test -f "{}" && git add "{}"' || true
